language: node_js
node_js:
  - 0.6

before_script:
  - ./node_modules/.bin/cake bam

script:
  - ./node_modules/.bin/coffeelint -r src
  - npm test

notifications:
  irc:
    - "irc.freenode.org#iks"
